
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #\u5FC3\u8DF3\u4FDD\u62A4,\u9ED8\u8BA4\u662Ftrue.\u5F00\u53D1\u6A21\u5F0F\u5EFA\u8BAE\u5173\u6389
  #\u4F1A\u7EDF\u8BA1\u4E0A\u7EBF\u7387,\u5982\u679C\u4E0D\u505C\u91CD\u542F,\u4F1A\u5F39\u51FA\u8B66\u544A
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka

